"""
This file is auto-generated by StellaNowCLI. DO NOT EDIT.

Model ID: 0bb918a9-d5d5-4210-a93e-8683f25f0f28
Generated: 2025-02-25T14:26:57Z
"""
from pydantic import BaseModel


class PhoneNumberModel(BaseModel):
    country_code: int
    number: int


"""
Generated from:

{
    "createdAt": "2025-02-25 14:25:00",
    "updatedAt": "2025-02-25 14:25:00",
    "id": "0bb918a9-d5d5-4210-a93e-8683f25f0f28",
    "name": "phone_number",
    "description": "",
    "fields": [
        {
            "id": "3c14a95d-6f21-44c5-accf-914d72c1e01d",
            "name": "country_code",
            "fieldType": {
                "value": "Integer"
            }
        },
        {
            "id": "05746ab2-84ea-4b77-adbb-8d91c22d050b",
            "name": "number",
            "fieldType": {
                "value": "Integer"
            }
        }
    ]
}
"""
