"""
This file is auto-generated by StellaNowCLI. DO NOT EDIT.

ID: 926abfe2-1f35-4819-9db3-293f9f1be8ac
Generated: 2025-03-30T20:18:50Z
"""

from pydantic import Field

from stellanow_sdk_python.messages.base import StellaNowBaseModel

from .address_model import AddressModel
from .phone_number_model import PhoneNumberModel


class ContactDetailsModel(StellaNowBaseModel):
    address: AddressModel = Field(None, serialization_alias="address")
    phone_number: PhoneNumberModel = Field(None, serialization_alias="phone_number")
    preferred: str = Field(None, serialization_alias="preferred")


"""
 Generated from:
{
    "createdAt": "2025-03-30 13:55:16",
    "updatedAt": "2025-03-30 13:56:26",
    "id": "926abfe2-1f35-4819-9db3-293f9f1be8ac",
    "name": "contact_details",
    "description": "",
    "fields": [
        {
            "id": "5b4d68f6-eeda-4188-9365-2368ebe21578",
            "name": "address",
            "fieldType": {
                "value": "Model",
                "modelRef": "8faf7ffa-8d84-4704-b50c-9b75606e609a"
            }
        },
        {
            "id": "6201b48f-b8d0-4adc-a17e-41cafb05b7dd",
            "name": "phone_number",
            "fieldType": {
                "value": "Model",
                "modelRef": "a253a0b1-4c3f-4397-bc19-44f1194885d5"
            }
        },
        {
            "id": "61ab8c2c-5934-412c-b10a-0bf84186bd1b",
            "name": "preferred",
            "fieldType": {
                "value": "String"
            }
        }
    ]
}
"""
