"""
This file is auto-generated by StellaNowCLI. DO NOT EDIT.

ID: a253a0b1-4c3f-4397-bc19-44f1194885d5
Generated: 2025-03-30T20:18:50Z
"""

from pydantic import Field

from stellanow_sdk_python.messages.base import StellaNowBaseModel


class PhoneNumberModel(StellaNowBaseModel):
    country_code: int = Field(None, serialization_alias="country_code")
    number: int = Field(None, serialization_alias="number")


"""
 Generated from:
{
    "createdAt": "2025-03-30 13:09:25",
    "updatedAt": "2025-03-30 13:09:25",
    "id": "a253a0b1-4c3f-4397-bc19-44f1194885d5",
    "name": "phone_number",
    "description": "",
    "fields": [
        {
            "id": "872a9440-7e5c-4ae6-a301-709e725ddbdd",
            "name": "country_code",
            "fieldType": {
                "value": "Integer"
            }
        },
        {
            "id": "4c5906dd-ff91-4580-9dc7-af50936400c0",
            "name": "number",
            "fieldType": {
                "value": "Integer"
            }
        }
    ]
}
"""
