name: Build and Test

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --sync

      - name: Check Version Against Existing Tags
        run: |
          VERSION=$(poetry version -s)  # Get version from pyproject.toml
          if git tag --list | grep -q "^v$VERSION$"; then
            echo "Error: Version v$VERSION already exists in tags. Please increment the version number."
            exit 1
          else
            echo "Version v$VERSION is new, proceeding with checks."
          fi

      - name: Check Formatting
        run: poetry run poe lint-check

      - name: Run Tests
        run: poetry run poe test