name: Create Release and Publish to PyPI

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Release and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --with dev --sync

      - name: Check Formatting
        run: poetry run poe lint-check

      - name: Run Tests
        run: poetry run poe test

      - name: Setup Git User
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Compute and push new version tag
        id: new-tag
        uses: stella-systems/github-actions/python-new-tag@master
        with:
          release-type: patch

      - name: Create a New Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        with:
          tag_name: v${{ steps.new-tag.outputs.release-version }}
          release_name: Release v${{ steps.new-tag.outputs.release-version }}
          body: ${{ env.COMMIT_MESSAGE }}
          draft: false
          prerelease: false

      - name: Build and Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
          RELEASE_VERSION: ${{ steps.new-tag.outputs.release-version }}
        run: |
          poetry version "$RELEASE_VERSION"
          poetry build
          poetry publish