"""
This file is auto-generated by StellaNowCLI. DO NOT EDIT.

ID: 753892fa-da1d-4b42-a468-be65a091673e
Generated: 2025-03-30T20:18:50Z
"""

from datetime import datetime

from pydantic import Field

from stellanow_sdk_python.messages.message import Entity, StellaNowMessageBase


class UserLoginMessage(StellaNowMessageBase):
    user_id: str = Field(None, serialization_alias="user_id")
    timestamp: datetime = Field(None, serialization_alias="timestamp")

    def __init__(self, patron: str, user_id: str, timestamp: datetime):
        super().__init__(
            event_name="user_login",
            entities=[Entity(entity_type_definition_id="patron", entity_id=patron)],
            user_id=user_id,
            timestamp=timestamp,
        )


"""
 Generated from:
{
    "createdAt": "2025-03-30 13:10:37",
    "updatedAt": "2025-03-30 13:11:16",
    "id": "753892fa-da1d-4b42-a468-be65a091673e",
    "name": "user_login",
    "projectId": "3af7b6f4-8afa-46ce-8df2-c9d86e8be3e9",
    "isActive": true,
    "description": "",
    "fields": [
        {
            "id": "2e367f2c-91c9-40b5-9a75-796877ed63d6",
            "name": "user_id",
            "fieldType": {
                "value": "String"
            },
            "required": true,
            "subfields": []
        },
        {
            "id": "e9320f99-fc4c-4b0c-ba5b-b66d0b2be178",
            "name": "timestamp",
            "fieldType": {
                "value": "DateTime"
            },
            "required": true,
            "subfields": []
        }
    ],
    "entities": [
        {
            "id": "194964c4-1caa-4347-9e91-5c275f9ba474",
            "name": "patron"
        }
    ]
}
"""
