"""
This file is auto-generated by StellaNowCLI. DO NOT EDIT.

ID: 4a1a8ff3-7ce7-4ba7-865a-e60f4a9f691b
Generated: 2025-03-30T20:18:50Z
"""

from pydantic import Field

from stellanow_sdk_python.messages.message import Entity, StellaNowMessageBase

from .models.contact_details_model import ContactDetailsModel


class UserDetailsUpdateExtendedMessage(StellaNowMessageBase):
    user_id: str = Field(None, serialization_alias="user_id")
    contact_details: ContactDetailsModel = Field(None, serialization_alias="contact_details")

    def __init__(self, patron: str, user_id: str, contact_details: ContactDetailsModel):
        super().__init__(
            event_name="user_details_update_extended",
            entities=[Entity(entity_type_definition_id="patron", entity_id=patron)],
            user_id=user_id,
            contact_details=contact_details,
        )


"""
 Generated from:
{
    "createdAt": "2025-03-30 13:58:11",
    "updatedAt": "2025-03-30 13:58:15",
    "id": "4a1a8ff3-7ce7-4ba7-865a-e60f4a9f691b",
    "name": "user_details_update_extended",
    "projectId": "3af7b6f4-8afa-46ce-8df2-c9d86e8be3e9",
    "isActive": true,
    "description": "",
    "fields": [
        {
            "id": "12ee07b3-65ca-407c-97fb-3d446f178f22",
            "name": "user_id",
            "fieldType": {
                "value": "String"
            },
            "required": true,
            "subfields": []
        },
        {
            "id": "7f8de09e-2052-4327-8fa2-41e1afcfb6e7",
            "name": "contact_details",
            "fieldType": {
                "value": "Model",
                "modelRef": "926abfe2-1f35-4819-9db3-293f9f1be8ac"
            },
            "required": false,
            "subfields": [
                {
                    "id": "f23be322-cace-4601-8ded-5cee8e2c1f8f",
                    "name": "address",
                    "fieldType": {
                        "value": "Model",
                        "modelRef": "8faf7ffa-8d84-4704-b50c-9b75606e609a"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "address"
                    ],
                    "modelFieldId": "5b4d68f6-eeda-4188-9365-2368ebe21578"
                },
                {
                    "id": "2261d8d4-c38b-4385-8912-fa513aa3d4c3",
                    "name": "city",
                    "fieldType": {
                        "value": "String"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "address",
                        "city"
                    ],
                    "modelFieldId": "aff56841-c0d6-4b65-b277-413091724d07"
                },
                {
                    "id": "f6166f9f-6f7c-41ce-b153-351fb2c6deb6",
                    "name": "country",
                    "fieldType": {
                        "value": "String"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "address",
                        "country"
                    ],
                    "modelFieldId": "9f48e2df-79c3-4d61-b1ac-bef22d4c60d0"
                },
                {
                    "id": "2af6bc92-6389-4b82-89d7-2b7503773388",
                    "name": "county",
                    "fieldType": {
                        "value": "String"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "address",
                        "county"
                    ],
                    "modelFieldId": "55ca7d08-fe78-4ebf-9092-123576c70ac1"
                },
                {
                    "id": "325336c7-a2bb-418d-b29c-2daaafe62871",
                    "name": "first_line",
                    "fieldType": {
                        "value": "String"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "address",
                        "first_line"
                    ],
                    "modelFieldId": "033b2474-2c5f-4ae2-bc91-5290ed3b1c5b"
                },
                {
                    "id": "9986c30d-8a33-46fa-94e4-b229645fb973",
                    "name": "post_code",
                    "fieldType": {
                        "value": "String"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "address",
                        "post_code"
                    ],
                    "modelFieldId": "c44df296-e14e-4801-85d5-060a3dabc0a7"
                },
                {
                    "id": "be158464-1c61-4092-b7d6-3e9c7b6cb19a",
                    "name": "second_line",
                    "fieldType": {
                        "value": "String"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "address",
                        "second_line"
                    ],
                    "modelFieldId": "8af2b111-633b-4e4b-8f9f-a1d8c34c7261"
                },
                {
                    "id": "43d89d93-1550-4035-957a-a64685a2a2f4",
                    "name": "phone_number",
                    "fieldType": {
                        "value": "Model",
                        "modelRef": "a253a0b1-4c3f-4397-bc19-44f1194885d5"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "phone_number"
                    ],
                    "modelFieldId": "6201b48f-b8d0-4adc-a17e-41cafb05b7dd"
                },
                {
                    "id": "ac218a0d-5c0e-4b3f-b2fa-0350a1a4c383",
                    "name": "country_code",
                    "fieldType": {
                        "value": "Integer"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "phone_number",
                        "country_code"
                    ],
                    "modelFieldId": "872a9440-7e5c-4ae6-a301-709e725ddbdd"
                },
                {
                    "id": "d83a951f-a4c7-4399-bcfd-fff6818a53ac",
                    "name": "number",
                    "fieldType": {
                        "value": "Integer"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "phone_number",
                        "number"
                    ],
                    "modelFieldId": "4c5906dd-ff91-4580-9dc7-af50936400c0"
                },
                {
                    "id": "1edeb9a8-4c45-4283-b841-e6a4d68e9775",
                    "name": "preferred",
                    "fieldType": {
                        "value": "String"
                    },
                    "required": true,
                    "path": [
                        "contact_details",
                        "preferred"
                    ],
                    "modelFieldId": "61ab8c2c-5934-412c-b10a-0bf84186bd1b"
                }
            ]
        }
    ],
    "entities": [
        {
            "id": "194964c4-1caa-4347-9e91-5c275f9ba474",
            "name": "patron"
        }
    ]
}
"""
