"""
This file is auto-generated by StellaNowCLI. DO NOT EDIT.

ID: 1e6cf72f-f4e0-4fe5-9fde-fae30bdbcb23
Generated: 2025-03-30T20:18:50Z
"""

from pydantic import Field

from stellanow_sdk_python.messages.message import Entity, StellaNowMessageBase

from .models.phone_number_model import PhoneNumberModel


class UserDetailsUpdateMessage(StellaNowMessageBase):
    user_id: str = Field(None, serialization_alias="user_id")
    phone_number: PhoneNumberModel = Field(None, serialization_alias="phone_number")

    def __init__(self, patron: str, user_id: str, phone_number: PhoneNumberModel):
        super().__init__(
            event_name="user_details_update",
            entities=[Entity(entity_type_definition_id="patron", entity_id=patron)],
            user_id=user_id,
            phone_number=phone_number,
        )


"""
 Generated from:
{
    "createdAt": "2025-03-30 13:08:56",
    "updatedAt": "2025-03-30 13:09:56",
    "id": "1e6cf72f-f4e0-4fe5-9fde-fae30bdbcb23",
    "name": "user_details_update",
    "projectId": "3af7b6f4-8afa-46ce-8df2-c9d86e8be3e9",
    "isActive": true,
    "description": "",
    "fields": [
        {
            "id": "d7227944-7360-47c8-adea-e07d13d64e44",
            "name": "user_id",
            "fieldType": {
                "value": "String"
            },
            "required": true,
            "subfields": []
        },
        {
            "id": "9dfa1e09-e95a-4479-be02-2fc28bd124b9",
            "name": "phone_number",
            "fieldType": {
                "value": "Model",
                "modelRef": "a253a0b1-4c3f-4397-bc19-44f1194885d5"
            },
            "required": false,
            "subfields": [
                {
                    "id": "43237d55-a3dc-40bc-b3a5-753a717b586f",
                    "name": "country_code",
                    "fieldType": {
                        "value": "Integer"
                    },
                    "required": true,
                    "path": [
                        "phone_number",
                        "country_code"
                    ],
                    "modelFieldId": "872a9440-7e5c-4ae6-a301-709e725ddbdd"
                },
                {
                    "id": "0d76e1f9-f78f-4d46-ac55-9625a8144258",
                    "name": "number",
                    "fieldType": {
                        "value": "Integer"
                    },
                    "required": true,
                    "path": [
                        "phone_number",
                        "number"
                    ],
                    "modelFieldId": "4c5906dd-ff91-4580-9dc7-af50936400c0"
                }
            ]
        }
    ],
    "entities": [
        {
            "id": "194964c4-1caa-4347-9e91-5c275f9ba474",
            "name": "patron"
        }
    ]
}
"""
